'\" t
.\"     Title: ip-array.conf
.\"    Author: AllKind <AllKind@BonBon.net>
.\" Generator: DocBook XSL-NS Stylesheets v1.74.3-pre <http://docbook.sf.net/>
.\"      Date: 01/12/2011
.\"    Manual: ip-array 0.80.00
.\"    Source: ip-array 0.80.00
.\"  Language: English
.\"
.TH "IP\-ARRAY\&.CONF" "8" "01/12/2011" "ip-array 0.80.00" "ip\-array 0\&.80\&.00"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ip-array.conf \- Configure the main configuration file of ip\-array (default: ip\-array\&.conf)
.SH "SYNOPSIS"
.sp
.nf
/etc/ip\-array/{stable|test}/conf\&.d/ip\-array\&.conf
.fi
.SH "DESCRIPTION"
.PP
.SH "SEE ALSO"
.PP

\fBip-array\fR(8),
\fBip-array_defaults.conf\fR(8),
\fBip-array_ruleblocks\fR(5),
\fBip-array_rulefiles\fR(5),
\fBip-array_templates\fR(5)
.SH "AUTHOR"
.PP
\fBAllKind\fR <\&AllKind@BonBon\&.net\&>
.RS 4
Some guy infront of a screen\&.
.RE
.RS 4
Thanks go to the open source community\&.
.RE
